const movies = [
  {id:1,title:"War 2",category:"Action",mood:"thrilling",language:"hi",poster:"images/war 2.jpg"},
  {id:2,title:"Tanvi",category:"Drama",mood:"inspirational",language:"hi",poster:"images/tanvi -upcoming.jpg"},
  {id:3,title:"sitare Zameen Par",category:"Drama",mood:"emotional",language:"hi",poster:"images/Sitaare-Zameen-Par.jpeg"},
  {id:4,title:"Sky Force",category:"Action",mood:"adventurous",language:"en",poster:"images/Sky-Force-.jpg"},
  {id:5,title:"Raid 2",category:"Action",mood:"thrilling",language:"hi",poster:"images/Raid2.jpg"},
  {id:6,title:"Saiyara",category:"Romance",mood:"romantic",language:"hi",poster:"images/Saiyaara.jpg"},
  {id:7,title:"Bhul Chuk Maaf",category:"Drama",mood:"emotional",language:"hi",poster:"images/Bhool-Chuk-Maaf.jpg"},
  {id:8,title:"Mission Impossible",category:"Action",mood:"thrilling",language:"en",poster:"images/Mission-Impossible-–.jpg"},
  {id:9,title:"Amateur",category:"Drama",mood:"inspirational",language:"en",poster:"images/Amateur-.jpg"},
  {id:10,title:"Chhorii 2",category:"Horror",mood:"thrilling",language:"hi",poster:"images/chhorii2.jpg"},
  {id:11,title:"Jewel Thief",category:"Thriller",mood:"thrilling",language:"hi",poster:"images/JewelThief-.jpeg"},
  {id:12,title:"Kesari Chapter 2",category:"Action",mood:"thrilling",language:"hi",poster:"images/KesariChapter2.jpeg"},
  {id:13,title:"Phule",category:"Drama",mood:"emotional",language:"hi",poster:"images/phule.jpg"},
  {id:14,title:"The Bhotni",category:"Horror",mood:"thrilling",language:"hi",poster:"images/The-Bhootnii-.jpeg"},
  {id:15,title:"Thunderbolts",category:"Action",mood:"adventurous",language:"en",poster:"images/thunderbolts.jpg"},
  {id:16,title:"Until Dawn",category:"Horror",mood:"thrilling",language:"en",poster:"images/untildawn.jpg"},
  {id:17,title:"BeHappy",category:"Comedy",mood:"happy",language:"hi",poster:"images/BeHappy.jpeg"},
{id:18,title:"Chhaava",category:"Historical",mood:"inspirational",language:"hi",poster:"images/Chhaava.jpg"},
{id:19,title:"DhoomDhaam",category:"Action",mood:"thrilling",language:"hi",poster:"images/dhoomdhaam.jpeg"},
{id:20,title:"Mere Husband Ki Biwi",category:"Comedy",mood:"funny",language:"hi",poster:"images/Mere husband ki biwi.jpeg"},
{id:21,title:"Mrs",category:"Drama",mood:"emotional",language:"hi",poster:"images/Mrs..jpg"},
{id:22,title:"Sikandar",category:"Action",mood:"motivational",language:"hi",poster:"images/Sikandar.jpeg"},
{id:23,title:"Thandel",category:"Thriller",mood:"intense",language:"hi",poster:"images/Thandel.jpg"},
{id:24,title:"The Diplomat",category:"Political",mood:"serious",language:"en",poster:"images/TheDiplomat.jpg"},
{id:25,title:"Tumko Meri Kasam",category:"Romance",mood:"romantic",language:"hi",poster:"images/Tumko-Meri-Kasam.jpg"},
{id:26,title:"Azaad",category:"Action",mood:"patriotic",language:"hi",poster:"images/Azaad.jpeg"},
{id:27,title:"Deva",category:"Action",mood:"intense",language:"hi",poster:"images/Deva.jpg"},
{id:28,title:"Emergency",category:"Political",mood:"serious",language:"hi",poster:"images/Emergency.jpg"},
{id:29,title:"Fateh",category:"Action",mood:"motivational",language:"hi",poster:"images/Fateh.jpg"},
{id:30,title:"GameChanger1",category:"Sci-Fi",mood:"thrilling",language:"hi",poster:"images/GameChanger1.jpg"},
{id:31,title:"Kraven the Hunter",category:"Action",mood:"dark",language:"en",poster:"images/Kraven-The-Hunter-.webp"},
{id:32,title:"Love is Forever",category:"Romance",mood:"romantic",language:"hi",poster:"images/love is forever.jpg"},
{id:33,title:"Loveyapa",category:"Romance",mood:"lighthearted",language:"hi",poster:"images/Loveyapa.jpg"},
{id:34,title:"Marco",category:"Drama",mood:"emotional",language:"hi",poster:"images/Marco.jpeg"},
{id:35,title:"Moana2",category:"Adventure",mood:"inspirational",language:"en",poster:"images/Moana2.jpg"},
{id:36,title:"Mufasa",category:"Animation",mood:"emotional",language:"en",poster:"images/Mufasa.jpg"},
{id:37,title:"Pushpa2",category:"Action",mood:"intense",language:"hi",poster:"images/Pushpa2.jpg"},
{id:38,title:"Wolf Man",category:"Horror",mood:"dark",language:"en",poster:"images/Wolf-Man.jpg"},
{id:39,title:"DoPatti",category:"Thriller",mood:"intense",language:"hi",poster:"images/Do-Patti.jpg"},
{id:40,title:"Ishq Vishk Rebound",category:"Romance",mood:"lighthearted",language:"hi",poster:"images/Ishq-Vishk-Rebound.jpg"},
{id:41,title:"Jigra",category:"Drama",mood:"emotional",language:"hi",poster:"images/Jigra.jpg"},
{id:42,title:"Joker",category:"Thriller",mood:"dark",language:"en",poster:"images/Joker.jpg"},
{id:43,title:"Kill",category:"Action",mood:"violent",language:"hi",poster:"images/Kill.jpg"},
{id:44,title:"Bhool Bhulaiya 3",category:"Horror-Comedy",mood:"mysterious",language:"hi",poster:"images/Bhool-Bhulaiyaa-3-.jpg"},
{id:45,title:"The Heist",category:"Crime",mood:"suspenseful",language:"en",poster:"images/The-Heist.jpg"},
{id:46,title:"Devara",category:"Action",mood:"intense",language:"hi",poster:"images/Devara-1.jpg"},
{id:47,title:"Sarfira",category:"Drama",mood:"inspirational",language:"hi",poster:"images/Sarfira-1.jpg"},
{id:48,title:"Venom",category:"Action",mood:"dark",language:"en",poster:"images/Venom-.jpg"},
{id:49,title:"Vicki Vidya Ka Wo Wala Video",category:"Comedy",mood:"funny",language:"hi",poster:"images/Vicky-Vidya-Ka-Woh-Wala video.jpg"},
{id:50,title:"Avatar: Fire and Ash",category:"Fantasy",mood:"epic",language:"en",poster:"images/Avatar-Fire-and-Ash-.jpg"},
{id:51,title:"Baaghi 4",category:"Action",mood:"thrilling",language:"hi",poster:"images/Baagi4.jpg"},
{id:52,title:"Dhadak 2",category:"Romance",mood:"emotional",language:"hi",poster:"images/Dhadak-2-.jpg"},
{id:53,title:"Haunted: Ghost of Past",category:"Horror",mood:"scary",language:"hi",poster:"images/Haunted-Ghosts-Of-The-Past-.jpg"},
{id:54,title:"Housefull 5",category:"Comedy",mood:"funny",language:"hi",poster:"images/Housefull-5-.jpg"},
{id:55,title:"Maa",category:"Drama",mood:"emotional",language:"hi",poster:"images/Maa.jpg"},
{id:56,title:"Param Sundari",category:"Romance",mood:"lighthearted",language:"hi",poster:"images/Param-Sundari.jpg"},
{id:57,title:"Teri Ishk Mein",category:"Romance",mood:"intense",language:"hi",poster:"images/Tere-Ishk-Mein-.jpeg"},
{id:58,title:"Animal",category:"Action",mood:"intense",language:"hi",poster:"images/Animal.jpg"},
{id:59,title:"Bahubali 2",category:"Action",mood:"epic",language:"hi",poster:"images/Bahubali-2-.jpg"},
{id:60,title:"Dangal",category:"Sports",mood:"inspirational",language:"hi",poster:"images/Dangal-.jpg"},
{id:61,title:"Gadar 2",category:"Action",mood:"patriotic",language:"hi",poster:"images/Gadar-2.jpg"},
{id:62,title:"Golmaal Again",category:"Comedy",mood:"funny",language:"hi",poster:"images/Golmaal again.jpg"},
{id:63,title:"Kaabil",category:"Thriller",mood:"emotional",language:"hi",poster:"images/Kaabil.jpg"},
{id:64,title:"Kalki",category:"Mythological",mood:"mysterious",language:"hi",poster:"images/Kalki.jpg"},
{id:65,title:"KGF 2",category:"Action",mood:"intense",language:"hi",poster:"images/KGF-2.jpg"},
{id:66,title:"Ok Janu",category:"Romance",mood:"lighthearted",language:"hi",poster:"images/Ok-Jaanu.jpg"},
{id:67,title:"Padmavat",category:"Historical",mood:"epic",language:"hi",poster:"images/Padmaavat.jpg"},
{id:68,title:"PK",category:"Comedy",mood:"thought-provoking",language:"hi",poster:"images/PK.jpg"},
{id:69,title:"Raees",category:"Crime",mood:"serious",language:"hi",poster:"images/Raees.jpg"},
{id:70,title:"Stree 2",category:"Horror Comedy",mood:"funny",language:"hi",poster:"images/Stree-2.jpg"},
{id:71,title:"Sultan",category:"Sports",mood:"motivational",language:"hi",poster:"images/Sultan.jpg"},
{id:72,title:"Tiger 3",category:"Action",mood:"patriotic",language:"hi",poster:"images/Tiger3.jpg"},
{id:73,title:"Brahmastra",category:"Fantasy",mood:"mystical",language:"hi",poster:"images/Brahmastra.jpg"},
{id:74,title:"Drishyam 2",category:"Thriller",mood:"suspenseful",language:"hi",poster:"images/Drishyam2.jpg"},
{id:75,title:"Fighter",category:"Action",mood:"patriotic",language:"hi",poster:"images/Fighter.jpg"},
{id:76,title:"Kerala Story",category:"Drama",mood:"serious",language:"hi",poster:"images/kerala story.jpg"},
{id:77,title:"Kashmir Files",category:"Drama",mood:"emotional",language:"hi",poster:"images/The-Kashmir-Files.jpg"},


];

